### ISSUE TITLE
是否可以把告警通知从告警规则中抽离出来

### ISSUE THREAD

**Issue by kubeop** [w8t-io/WatchAlert#65]
是否可以把告警通知从告警规则中抽离出来，单独为一个告警订阅，可以根据标签、分组等条件订阅告警发送给对应的通知对象

**Comment by Cairry** [comment]
我似乎理解你的想法。但是我觉得你的需求是另外的功能，称为告警订阅 它是用来以用户的角度选择性的通知到具体的人。

如果从告警通知中抽离出来后，没有明确的通知目标，则会产生一种现象，那么就是当告警来了并不会触发通知，只有订阅了告警才会通知。我觉得这个需求可能不太合理。

或许我的理解有问题，你也可以详细的描述一下。

**Comment by kubeop** [comment]
事实上在Prometheus里，配置了告警触发了之后是没有通知目标的，而是丢给AlertManager，根据AlertManager的receivers配置进行通知。这个告警订阅的逻辑类似配置AlertManager的receivers，在Prometheus

**Comment by Cairry** [comment]
根据目前的逻辑，告警规则中的通知对象 = 等同于 AlertManager的receivers。
---
我大概理解你下面的需求了。假设存在大量业务线，你希望通过告警订阅的方式，来选择性订阅哪些规则，并且将已订阅的规则推送至当前告警订阅中的通知对象。

按照这种逻辑的话似乎需要将通知对象与告警订阅进行合并。

**Comment by Cairry** [comment]
感谢你的反馈和建议，如果可以希望能够进群进一步沟通。
