### ISSUE TITLE
关于支持自定义Webhook告警，限定告警资源总额

### ISSUE THREAD

**Issue by VobileLiuZhiwu** [w8t-io/WatchAlert#91]
我这里有个需求，比如我司的某个业务线，会使用钉钉机器人发送群聊消息进行告警通知，但钉钉机器人每月发送的消息总量是限定的，比如5万条。

如果不小心用超了，这个月就没法在钉钉群里发出告警通知了。只能想办法走短信或电话/邮件。

在这种场景下，应该需要记录并限制告警的频率与额度。但我找遍了全网，居然没发现有哪个开源库和产品(比如快猫的flashduty)有实现这类功能。

是我提出的这种解法不对吗？不应该限制？而应该强调治理？我觉得是否应该治理和限制都要有呢？

WatchAlert是否会做出这样的功能支持呢？

**Comment by Cairry** [comment]
ok，我理解你的意思。

这个功能其实不是很合理，当然我认为其他产品可能会有类似的通知限制（SAAS版 或许是收费项），做这个功能可能是没有必要的。

最好的方式，通过优化其规则 / 在第三方做好相关的约束配置，避免超额使用。
